/**
 * Application state for Builder IA
 */

import type { Source } from '@dsfr-data/shared';

// Source is imported from @dsfr-data/shared (unified interface)
export type { Source } from '@dsfr-data/shared';

/** Analyzed field metadata */
export interface Field {
  name: string;
  type: string;
  sample: unknown;
}

/** Chart configuration generated by the AI */
export interface ChartConfig {
  type:
    | 'bar'
    | 'line'
    | 'pie'
    | 'doughnut'
    | 'radar'
    | 'horizontalBar'
    | 'scatter'
    | 'gauge'
    | 'kpi'
    | 'map'
    | 'bar-line'
    | 'map-reg'
    | 'datalist'
    | 'podium';
  labelField?: string;
  valueField: string;
  valueField2?: string;
  /** Séries supplementaires (format LARGE) : une colonne numerique par série. */
  valueFields?: string[];
  codeField?: string;
  aggregation?: 'sum' | 'avg' | 'count' | 'min' | 'max';
  limit?: number;
  sortOrder?: 'desc' | 'asc';
  title?: string;
  subtitle?: string;
  color?: string;
  color2?: string;
  variant?: 'info' | 'success' | 'warning' | 'error';
  unit?: string;
  palette?: string;
  colonnes?: string;
  pagination?: number;
  where?: string;
  data2?: AggregatedResult[];
}

/** A single aggregated data result */
export interface AggregatedResult {
  label: string;
  value: number;
  code?: string | null;
}

/** Chat message */
export interface Message {
  role: 'user' | 'assistant';
  content: string;
}

/** Application state shape */
export interface AppState {
  source: Source | null;
  localData: Record<string, unknown>[] | null;
  fields: Field[];
  chartConfig: ChartConfig | null;
  chart: unknown | null;
  messages: Message[];
  isThinking: boolean;
}

/** Global application state singleton */
export const state: AppState = {
  source: null,
  localData: null,
  fields: [],
  chartConfig: null,
  chart: null,
  messages: [],
  isThinking: false,
};
